import Providers from "@/components/Provider";
import Link from "next/link";
import "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="m-10 grid justify-items-start gap-4 bg-orange-200">
        <Providers>
          <Link
            href="/"
            className="p-2 border border-blue-600 grid justify-center"
          >
            Home
          </Link>
          {children}
        </Providers>
      </body>
    </html>
  );
}
